
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 27 16:38:05 CEST 2014
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 22;
  public static final int AND = 25;
  public static final int MENOS = 18;
  public static final int READ = 11;
  public static final int MENOR = 15;
  public static final int ELSE = 7;
  public static final int OR = 24;
  public static final int IGUAL = 23;
  public static final int INT = 13;
  public static final int THEN = 6;
  public static final int SEMI = 2;
  public static final int END = 8;
  public static final int END_BLOCK = 4;
  public static final int IDEN = 29;
  public static final int TRUE = 28;
  public static final int IF = 5;
  public static final int NEW_BLOCK = 3;
  public static final int WRITE = 12;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int PAP = 21;
  public static final int FALSE = 27;
  public static final int PROD = 19;
  public static final int error = 1;
  public static final int UNTIL = 10;
  public static final int EQ = 16;
  public static final int BOOL = 14;
  public static final int REPEAT = 9;
  public static final int MAS = 17;
}

